name: CD authentication-api
on:
  push:
    branches: 
    - master
    paths:
      - 'authentication-api/**'

jobs:
  build-and-deploy:
    name: Deploy authentication-api to Heroku
    runs-on: ubuntu-latest
    env:
      HEROKU_EMAIL: ${{ secrets.AUTHENTICATION_API__HEROKU_EMAIL }}
      HEROKU_TOKEN: ${{ secrets.AUTHENTICATION_API__HEROKU_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to Heroku
      run: cd authentication-api && make deploy_test
