name: CD lesson-api
on:
  push:
    branches: 
    - master
    paths:
      - 'lesson-api/**'

jobs:
  build-and-deploy:
    name: Deploy lesson-api to Heroku
    runs-on: ubuntu-latest
    env:
      HEROKU_EMAIL: ${{ secrets.LESSON_API__HEROKU_EMAIL }}
      HEROKU_TOKEN: ${{ secrets.LESSON_API__HEROKU_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to Heroku
      run: cd lesson-api && make deploy_test
